# Generated by Django 5.0.3 on 2024-03-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_detail_patient_address_patient_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='medicine_detail',
            field=models.TextField(null=True),
        ),
    ]
