# Generated by Django 5.0.3 on 2024-03-20 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patient_medicine_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Detail',
            new_name='detail',
        ),
    ]
