# Generated by Django 5.0.3 on 2024-03-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_rename_detail_patient_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='added_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
