# Generated by Django 5.0.3 on 2024-03-22 02:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_patient_added_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='visit_date',
            field=models.DateField(default=datetime.date(2024, 3, 22), null=True),
        ),
    ]
