# Generated by Django 5.0.3 on 2024-03-26 12:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_patient_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='medicine_detail',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='next_visit',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='note',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='visit_date',
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(null=True)),
                ('medicine_detail', models.TextField(null=True)),
                ('note', models.TextField(null=True)),
                ('next_visit', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('visit_date', models.DateField(default=datetime.date(2024, 3, 26), null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
